
create table
  public.users (
    id bigint generated by default as identity not null,
    name text null,
    password text null,
    created_at timestamp with time zone not null default now(),
    deleted boolean null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;