create table
  public.events (
    id bigint generated by default as identity not null,
    author bigint not null,
    title text not null,
    start_time timestamp with time zone not null default now(),
    end_time timestamp with time zone not null,
    institute bigint not null,
    created_at timestamp with time zone not null default now(),
    cancelled boolean not null default false,
    type bigint not null,
    location text null,
    constraint events_pkey primary key (id),
    constraint events_author_fkey foreign key (author) references users (id),
    constraint events_institute_fkey foreign key (institute) references institutes (id),
    constraint events_type_fkey foreign key (
      type
    ) references event_types (id)
  ) tablespace pg_default;